# ASSIGNMENT 2
Name: Mohammad Irfan Iskandar Bin Zainuddin(A18CS0111)

Topic: Numpy and Pandas

#    NUMPY

In [1]:
import numpy as np
#TASK1
#Read the "Attendance_RAW.txt and save the data into nummpy array"
readFile=open("Attendance_RAW.txt","r")
attendance=[]
for line in readFile:
    #removing the \n character from a single line
    line=int(line.strip())
    attendance.append(line)
print(attendance)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1]


In [2]:
#TASK2
#reshape the array so that ROWS represents employees, COLUMNS represent working days
Arr=np.array(attendance).reshape(14,15).T
print(Arr)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 0 1 1 1 1 0 1]
 [1 1 0 1 0 1 1 0 1 0 1 1 1 1]
 [1 1 1 1 0 1 0 1 1 0 1 0 1 1]
 [1 1 0 0 0 1 1 0 0 0 1 0 1 0]
 [1 1 0 1 0 0 1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 0 1 0 1 1 0 1 0]
 [1 0 1 1 1 1 0 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 0 1 0 1 1 1 1 1 1]
 [1 1 0 0 1 0 1 1 1 1 1 1 1 1]
 [0 1 1 0 1 1 1 0 1 1 1 1 0 1]]


In [3]:
#TASK3
#construct a function that can caluclate and return the list of average of attendance for each day
def averagePerDay():
    return np.mean(Arr,axis=0)
att=averagePerDay()
rounded_att=[round(x,2) for x in att]
print(rounded_att) 

[0.93, 0.93, 0.67, 0.67, 0.73, 0.73, 0.73, 0.6, 0.73, 0.67, 1.0, 0.67, 0.8, 0.67]


# PANDAS

In [ ]:
import pandas as pd
#TASK1
#using pondas library, read the CSV data file in python into a varibale emp_detail
emp_detail=pd.read_csv("emp_detail.csv")
emp_detail.index = np.arange(1, len(emp_detail)+1)

In [ ]:
#TASK2
#Display the first five rows of records of the data read in step 1.
emp_detail.head()

In [ ]:
#TASK3
#Using the Numpy object of the attendance record created earlier:
#[a]Convert the Numpy object into Data Frame, name it attendance
#attendance=pd.DataFrame(Arr, index=range(1,len(attendance.index)+1))
attendance=pd.DataFrame(Arr,index=range(1,np.shape(Arr)[0]+1),columns=range(1,np.shape(Arr)[1]+1))
attendance

#[b] Merge the DataFrames emp_detail and attendance into a new data frame, name it emp_attendance
emp_attendance=pd.concat([emp_detail,attendance],axis=1,)
emp_attendance

In [ ]:
#Task4
#add a column with name "total"into the emp_attendance Data Frame that consits of the total no of days
#the employee attended the event
emp_attendance["total"]=np.sum(Arr,axis=1)
emp_attendance

In [ ]:
#TASK5
#Add a column with name "rate" into the emp_attendance DataFrame that consits of the attendance
#rate/percentage the employee throughout the 14 days
emp_attendance["rate"]=round((emp_attendance["total"]/np.shape(Arr)[1]),2)
emp_attendance

In [ ]:
#TASK6
#consider te following rules in classify the attendance
#a. Rate>90%:Good
#b. 60%<Rate<90%:Moderate
#c Rate<60%:Bad
#Based on the grouping rule above, get the status for each of the staff and save the status in a
#new column "status" in the Data Frame
emp_attendance["status"]=np.where(emp_attendance["rate"]>0.9,"Good"
                                  ,np.where(emp_attendance["rate"]<0.6,"Bad","Moderate"))
emp_attendance

In [ ]:
#TASK7
#construct a function that returns the average attendance of all staff over the 14 days according
#to the department
def averageDepartment(frame):
    avgFrame=pd.DataFrame(frame.groupby("Department").mean())
    avgFrame.rename(columns={"rate":"Average"},inplace=True)
    return avgFrame

new_emp=emp_attendance.copy()
new_emp=new_emp.drop(["status"],axis=1)
averageDepartment(new_emp)