In [1]:
import numpy as np

attendance = np.array([1,0,0,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,1,1,1,1])
name_list = np.array(["Ali","Ahmad","Beng","Chris","Sita","Marion","Stephen","Cobby","Akmal","Nita"])
day_list = np.array(["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])
print(attendance)
#print(len(attendance))
print()
print(name_list)
print()
print(day_list)

[1 0 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1]

['Ali' 'Ahmad' 'Beng' 'Chris' 'Sita' 'Marion' 'Stephen' 'Cobby' 'Akmal'
 'Nita']

['Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday']


## Description of the data:
Given a list of attendance data of an event for 10 students for 1 week where **1 indicates the student attends** for the event, while **0 indicates the student is absent**. The data is given in a simple list described as follows:

<br>
<img src="F1.png">

The namelist and the daylist also given. The order of the day and name in the attendance data are complement to both variables. 

In [2]:
# Now, based on the given attendance data, create a 2D numpy array (named: attendance_arr) where:
# ROW represents each student
# COLUMN represents each day
# Write the code at below:
attendance_arr=attendance.reshape(7,10).T
print(attendance_arr)

[[1 1 0 1 1 1 1]
 [0 1 1 0 1 0 1]
 [0 1 0 1 1 0 1]
 [1 1 0 1 1 0 0]
 [1 1 1 1 1 0 0]
 [1 1 1 1 1 0 0]
 [0 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 1 1 0 1 1 1]
 [1 1 1 1 1 1 1]]


In [3]:
# Write a fuction that returns the list of names, and their corresponding total attendance based on a filter
# The function should accept at least ONE argument, which is the no. of days. You should return the results
# filtered based on the no. of days. 
# E.g.: get the names and their total attendance for those who attended more than 4 days
def getList(days):
    i=0
    total=attendance_arr.sum(axis=1)
    print(total)
    for a in total:
        if a<=days:
            total[i]=0
        i+=1
    print(total)
    return total
       
y=getList(6)
index=0
for name in name_list:
    if y[index]!=0:
        print(name,y[index])
    index+=1

[6 4 4 4 5 5 5 6 5 7]
[0 0 0 0 0 0 0 0 0 7]
Nita 7


In [4]:
# Write a function that returns the 7-day attendance for a specific person.
# The function should accept at least ONE argument, which is the name of the person. You should return the results
# based on the name.
# E.g.: get the 7-day attendance for "Akmal"
def someone(name):
    i=0
    for x in name_list:
        if x==name:
             return attendance_arr[i]
        i+=1
print("Akmal attendance Record: ",someone("Akmal"))

Akmal attendance Record:  [0 1 1 0 1 1 1]


In [5]:
# Write a fuction that returns the list of days, and the corresponding total attendance based on a filter
# The function should accept at least ONE argument, which is the no. of attendees. You should return the results
# filtered based on the no. of attendees. 
# E.g.: get the list of days and the total attendance for where if the attendees exceed 5 people. 
def getDay(attendees):
    total=attendance_arr.sum(axis=0)
    print(total)
    index=0
    for a in total:
        if a<=attendees:
            total[index]=0
        index+=1
    print(total)
    return total

x=getDay(5)
index=0
for a in day_list:
    if x[index]!=0:
        print(a,x[index])
    index+=1

[ 6 10  7  6 10  5  7]
[ 6 10  7  6 10  0  7]
Sunday 6
Monday 10
Tuesday 7
Wednesday 6
Thursday 10
Saturday 7


In [6]:
# Write a function that returns the percentage of attendance for each day.
def percentageDay():
    return ((attendance_arr.sum(axis=0)/10)*100)
x=percentageDay()
index=0
for y in day_list:
    print(y," = ",x[index],"%")
    index+=1

Sunday  =  60.0 %
Monday  =  100.0 %
Tuesday  =  70.0 %
Wednesday  =  60.0 %
Thursday  =  100.0 %
Friday  =  50.0 %
Saturday  =  70.0 %


In [7]:
# Write a function that returns the percentage of attendance for each student.
def percentageStudent():
    return ((attendance_arr.sum(axis=1)/7)*100)
a=percentageStudent()
index=0
for b in name_list:
    print(b," = ",round(a[index],2),"%")
    index+=1

Ali  =  85.71 %
Ahmad  =  57.14 %
Beng  =  57.14 %
Chris  =  57.14 %
Sita  =  71.43 %
Marion  =  71.43 %
Stephen  =  71.43 %
Cobby  =  85.71 %
Akmal  =  71.43 %
Nita  =  100.0 %
