In [1]:
import numpy as np

attendance = np.array([1,0,0,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,1,1,1,1])
name_list = np.array(["Ali","Ahmad","Beng","Chris","Sita","Marion","Stephen","Cobby","Akmal","Nita"])
day_list = np.array(["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])

print(attendance)
print(len(attendance))
print()
print(name_list)
print()
print(day_list)

[1 0 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1]
70

['Ali' 'Ahmad' 'Beng' 'Chris' 'Sita' 'Marion' 'Stephen' 'Cobby' 'Akmal'
 'Nita']

['Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday']


## Description of the data:
Given a list of attendance data of an event for 10 students for 1 week where **1 indicates the student attends** for the event, while **0 indicates the student is absent**. The data is given in a simple list described as follows:

<br>
<img src="F1.png">

The namelist and the daylist also given. The order of the day and name in the attendance data are complement to both variables. 

In [2]:
# Now, based on the given attendance data, create a 2D numpy array (named: attendance_arr) where:
# ROW represents each student
# COLUMN represents each day
# Write the code at below:
attendance_arr=np.array(attendance).reshape(7,10).T
print(attendance_arr)

[[1 1 0 1 1 1 1]
 [0 1 1 0 1 0 1]
 [0 1 0 1 1 0 1]
 [1 1 0 1 1 0 0]
 [1 1 1 1 1 0 0]
 [1 1 1 1 1 0 0]
 [0 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 1 1 0 1 1 1]
 [1 1 1 1 1 1 1]]


In [3]:
# Write a fuction that returns the list of names, and their corresponding total attendance based on a filter
# The function should accept at least ONE argument, which is the no. of days. You should return the results
# filtered based on the no. of days. 
# E.g.: get the names and their total attendance for those who attended more than 4 days
def total_attendance(day):
    mapping={}
    total=np.sum(attendance_arr,axis=1)
    i=0
    for name in name_list:
        mapping[name]=total[i]
        if mapping[name]<=day:
            del mapping[name]
        i+=1
    return mapping

result=total_attendance(4)
print(result)

{'Ali': 6, 'Sita': 5, 'Marion': 5, 'Stephen': 5, 'Cobby': 6, 'Akmal': 5, 'Nita': 7}


In [4]:
# Write a function that returns the 7-day attendance for a specific person.
# The function should accept at least ONE argument, which is the name of the person. You should return the results
# based on the name.
# E.g.: get the 7-day attendance for "Akmal"

def personAttendance(name):
    index=0
    for nama in name_list:
        if nama==name:
            return attendance_arr[index,:]
        index+=1
            
    
PersonResult=personAttendance('Akmal')
print(PersonResult)

[0 1 1 0 1 1 1]


In [5]:
# Write a fuction that returns the list of days, and the corresponding total attendance based on a filter
# The function should accept at least ONE argument, which is the no. of attendees. You should return the results
# filtered based on the no. of attendees. 
# E.g.: get the list of days and the total attendance for where if the attendees exceed 5 people. 

def getDay(number):
    mapping={}
    total=np.sum(attendance_arr,axis=0)
    i=0
    for day in day_list:
        mapping[day]=total[i]
        if mapping[day]<=number:
            del mapping[day]
        i+=1
    return mapping

DayResult=getDay(5)
print(DayResult)

{'Sunday': 6, 'Monday': 10, 'Tuesday': 7, 'Wednesday': 6, 'Thursday': 10, 'Saturday': 7}


In [6]:
# Write a function that returns the percentage of attendance for each day.

def percentageDay():
    mappingDay={}
    total=(np.sum(attendance_arr,axis=0)/10)*100
    i=0
    for day in day_list:
        mappingDay[day]=total[i]
        i+=1
    return mappingDay

resultDay=percentageDay()
print(resultDay)

{'Sunday': 60.0, 'Monday': 100.0, 'Tuesday': 70.0, 'Wednesday': 60.0, 'Thursday': 100.0, 'Friday': 50.0, 'Saturday': 70.0}


In [7]:
# Write a function that returns the percentage of attendance for each student.
def percentageStudent():
    mappingStudent={}
    total=(np.sum(attendance_arr,axis=1)/7)*100
    i=0
    for student in name_list:
        mappingStudent[student]=round(total[i],2)
        i+=1
    return mappingStudent

resultStudent=percentageStudent()
print(resultStudent)

{'Ali': 85.71, 'Ahmad': 57.14, 'Beng': 57.14, 'Chris': 57.14, 'Sita': 71.43, 'Marion': 71.43, 'Stephen': 71.43, 'Cobby': 85.71, 'Akmal': 71.43, 'Nita': 100.0}
