In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA

In [2]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])
data 

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [3]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [4]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [5]:
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [6]:
data.dropna(how='all',axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [7]:
data[5]=range(len(data))
data

0    1    2   4  5
0  1.0  6.5  3.0 NaN  0
1  1.0  NaN  NaN NaN  1
2  NaN  NaN  NaN NaN  2
3  NaN  6.5  3.0 NaN  3

In [8]:
data.dropna(axis=1)

5
0  0
1  1
2  2
3  3

In [9]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.737574       NaN       NaN
1 -1.827287       NaN       NaN
2  2.082398       NaN  0.376282
3 -0.943451       NaN -0.702357
4  0.719594 -0.389813 -0.288818
5 -0.109246 -1.084826 -0.362977
6 -0.064499  1.113387  0.855959

In [10]:
df.dropna(thresh=3)

0         1         2
4  0.719594 -0.389813 -0.288818
5 -0.109246 -1.084826 -0.362977
6 -0.064499  1.113387  0.855959

In [11]:
df

0         1         2
0  0.737574       NaN       NaN
1 -1.827287       NaN       NaN
2  2.082398       NaN  0.376282
3 -0.943451       NaN -0.702357
4  0.719594 -0.389813 -0.288818
5 -0.109246 -1.084826 -0.362977
6 -0.064499  1.113387  0.855959

In [12]:
df.fillna('unknown')

0         1         2
0  0.737574   unknown   unknown
1 -1.827287   unknown   unknown
2  2.082398   unknown  0.376282
3 -0.943451   unknown -0.702357
4  0.719594 -0.389813 -0.288818
5 -0.109246  -1.08483 -0.362977
6 -0.064499   1.11339  0.855959

In [13]:
df.fillna({1:'unknown_1',
             2: 'unknown_2'})

0          1          2
0  0.737574  unknown_1  unknown_2
1 -1.827287  unknown_1  unknown_2
2  2.082398  unknown_1   0.376282
3 -0.943451  unknown_1  -0.702357
4  0.719594  -0.389813  -0.288818
5 -0.109246   -1.08483  -0.362977
6 -0.064499    1.11339   0.855959

In [14]:
df.fillna(0,inplace=True)

In [15]:
df

0         1         2
0  0.737574  0.000000  0.000000
1 -1.827287  0.000000  0.000000
2  2.082398  0.000000  0.376282
3 -0.943451  0.000000 -0.702357
4  0.719594 -0.389813 -0.288818
5 -0.109246 -1.084826 -0.362977
6 -0.064499  1.113387  0.855959

In [16]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df 

0         1         2
0  2.146187 -1.537749  0.698241
1  0.364796 -0.130888 -0.565899
2 -1.205471       NaN -0.272952
3  0.370244       NaN  0.686456
4 -0.886887       NaN       NaN
5  1.066484       NaN       NaN

In [17]:
df.fillna(method='ffill')

0         1         2
0  2.146187 -1.537749  0.698241
1  0.364796 -0.130888 -0.565899
2 -1.205471 -0.130888 -0.272952
3  0.370244 -0.130888  0.686456
4 -0.886887 -0.130888  0.686456
5  1.066484 -0.130888  0.686456

In [18]:
df.fillna(method='ffill',limit=2)

0         1         2
0  2.146187 -1.537749  0.698241
1  0.364796 -0.130888 -0.565899
2 -1.205471 -0.130888 -0.272952
3  0.370244 -0.130888  0.686456
4 -0.886887       NaN  0.686456
5  1.066484       NaN  0.686456

In [19]:
df

0         1         2
0  2.146187 -1.537749  0.698241
1  0.364796 -0.130888 -0.565899
2 -1.205471       NaN -0.272952
3  0.370244       NaN  0.686456
4 -0.886887       NaN       NaN
5  1.066484       NaN       NaN

In [20]:
(0.447240+-1.050007)/2

-0.3013834999999999

In [21]:
df.fillna({1:df[1].mean(),
              2: df[2].mean()})

0         1         2
0  2.146187 -1.537749  0.698241
1  0.364796 -0.130888 -0.565899
2 -1.205471 -0.834319 -0.272952
3  0.370244 -0.834319  0.686456
4 -0.886887 -0.834319  0.136462
5  1.066484 -0.834319  0.136462

# DATA TRANSFORMATION

In [22]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates(keep='last')

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4

In [25]:
data['k1'].duplicated()

0    False
1    False
2     True
3     True
4     True
5     True
6     True
Name: k1, dtype: bool

In [26]:
data['k2'].duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
Name: k2, dtype: bool

In [27]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [28]:
data.replace(-999,0.0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [29]:
data.replace([-999,-1000],0.0)

0    1.0
1    0.0
2    2.0
3    0.0
4    0.0
5    3.0
dtype: float64

In [30]:
data.replace({-999:0.1,
                      -1000:0.5})

0    1.0
1    0.1
2    2.0
3    0.1
4    0.5
5    3.0
dtype: float64

In [31]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], 
                    columns=['one', 'two', 'three', 'four']) 
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [32]:
data.T

Ohio  Colorado  New York
one       0         4         8
two       1         5         9
three     2         6        10
four      3         7        11

In [33]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [34]:
index=list(data.index)
index

['Ohio', 'Colorado', 'New York']

In [35]:
transform=[x.upper() for x in index]
transform

['OHIO', 'COLORADO', 'NEW YORK']

In [36]:
data.index=transform
data.index

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [37]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [38]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [39]:
data.rename(index=str.title,columns=str.title)

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [40]:
 data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

# Discretization and Binning

In [42]:
ages=[x for x in range(10,101,10)]
ages

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [45]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] 
bins=[18,25,32,60,100]
cats=pd.cut(ages,bins)

cats

[(18, 25], (18, 25], (18, 25], (25, 32], (18, 25], ..., (25, 32], (60, 100], (32, 60], (32, 60], (25, 32]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 32] < (32, 60] < (60, 100]]

In [47]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [48]:
cats.categories

IntervalIndex([(18, 25], (25, 32], (32, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [49]:
pd.value_counts(cats)

(18, 25]     5
(32, 60]     3
(25, 32]     3
(60, 100]    1
dtype: int64

In [50]:
cats.value_counts()

(18, 25]     5
(25, 32]     3
(32, 60]     3
(60, 100]    1
dtype: int64

In [52]:
x=pd.cut(ages,[18,25,32,60,100],right=False)
x

[[18, 25), [18, 25), [25, 32), [25, 32), [18, 25), ..., [25, 32), [60, 100), [32, 60), [32, 60), [32, 60)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 32) < [32, 60) < [60, 100)]

In [54]:
x.codes

array([0, 0, 1, 1, 0, 0, 2, 1, 3, 2, 2, 2], dtype=int8)

In [58]:
x.value_counts()

[18, 25)     4
[25, 32)     3
[32, 60)     4
[60, 100)    1
dtype: int64

In [59]:
ages

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [62]:
bins

[18, 25, 32, 60, 100]

In [63]:
group_names=['Youth','YoungAdult','MiddleAged','Senior']
grouping=pd.cut(ages,bins,labels=group_names)

grouping

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [64]:
grouping.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [65]:
grouping.value_counts()

Youth         5
YoungAdult    3
MiddleAged    3
Senior        1
dtype: int64

In [66]:
num=[1,2,3]
a,b,c=num
print(a)
print(b)
print(c)

1
2
3


In [67]:
nama='irfan'
selit='kacak'

selit.join(nama)

'ikacakrkacakfkacakakacakn'

# Regular Expression

In [69]:
person='''dave is
to good to be true'''
print(person)

dave is
to good to be true


In [70]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [71]:
data.index=range(1,len(data)+1)

In [72]:
data

1    dave@google.com
2    steve@gmail.com
3      rob@gmail.com
4                NaN
dtype: object